import {
  Document, Packer, Paragraph, TextRun, AlignmentType,
  Table, TableRow, TableCell, WidthType, BorderStyle, VerticalAlign,
  convertMillimetersToTwip, PageBreak, Header, Footer, PageNumber,
} from 'docx';
import fs from 'fs';

const FONT = 'Times New Roman';
const SZ = 26; // 13pt
const margins = { top: convertMillimetersToTwip(20), bottom: convertMillimetersToTwip(20), left: convertMillimetersToTwip(35), right: convertMillimetersToTwip(20) };
const sp12 = { before: 120, after: 0, line: 288 };

const p = (text, opts = {}) => new Paragraph({
  spacing: opts.spacing ?? sp12,
  indent: opts.noIndent ? undefined : { firstLine: convertMillimetersToTwip(12.7) },
  alignment: opts.align ?? AlignmentType.JUSTIFIED,
  children: Array.isArray(text) ? text : [new TextRun({ text, font: FONT, size: opts.size ?? SZ, bold: opts.bold ?? false, italics: opts.italic ?? false })],
});
const center = (text, sz = SZ, bold = true) => p(text, { align: AlignmentType.CENTER, size: sz, bold, noIndent: true });
const h1 = (t) => new Paragraph({ spacing: { before: 360, after: 120 }, children: [new TextRun({ text: t.toUpperCase(), font: FONT, size: 28, bold: true })] });
const h2 = (t) => new Paragraph({ spacing: { before: 240, after: 100 }, children: [new TextRun({ text: t, font: FONT, size: SZ, bold: true })] });
const h3 = (t) => new Paragraph({ spacing: { before: 180, after: 60 }, indent: { firstLine: convertMillimetersToTwip(12.7) }, children: [new TextRun({ text: t, font: FONT, size: SZ, bold: true })] });
const empty = () => new Paragraph({ children: [] });
const bullet = (t) => p(`- ${t}`, { spacing: { before: 60, after: 0, line: 288 } });
const pageBreak = () => new Paragraph({ children: [new TextRun({ children: [new PageBreak()] })] });

function makeTable(headers, rows) {
  const b = { style: BorderStyle.SINGLE, size: 1, color: '000000' };
  const borders = { top: b, bottom: b, left: b, right: b };
  return new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [
    new TableRow({ children: headers.map(h => new TableCell({ borders, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.CENTER, spacing: { before: 40, after: 40 }, children: [new TextRun({ text: h, font: FONT, size: 24, bold: true })] })] })) }),
    ...rows.map(row => new TableRow({ children: row.map(c => new TableCell({ borders, verticalAlign: VerticalAlign.CENTER, children: [new Paragraph({ alignment: AlignmentType.LEFT, spacing: { before: 30, after: 30 }, indent: { left: 100 }, children: [new TextRun({ text: String(c), font: FONT, size: 24 })] })] })) })),
  ]});
}

function multiParagraphs(texts) { return texts.map(t => t === '' ? empty() : p(t)); }

// ======================== COVER PAGE ========================
const coverPage = {
  properties: { page: { margin: margins } },
  children: [
    center('BỘ GIÁO DỤC VÀ ĐÀO TẠO', SZ, true),
    center('TRƯỜNG ĐẠI HỌC TÂY ĐÔ', SZ, true),
    center('KHOA KỸ THUẬT – CÔNG NGHỆ', SZ, true),
    empty(), empty(), empty(), empty(), empty(),
    center('TIỂU LUẬN TỐT NGHIỆP', 36, true),
    empty(),
    center('XÂY DỰNG WEBSITE ĐẶT PHÒNG KHÁCH SẠN', 32, true),
    center('TRỰC TUYẾN SỬ DỤNG MERN STACK', 32, true),
    empty(), empty(), empty(), empty(), empty(), empty(), empty(), empty(),
    p('Ngành: Công nghệ thông tin', { noIndent: true, align: AlignmentType.LEFT }),
    p('Mã ngành: 7480201', { noIndent: true, align: AlignmentType.LEFT }),
    empty(), empty(),
    p('Sinh viên thực hiện: Nguyễn Văn A', { noIndent: true, align: AlignmentType.LEFT }),
    p('MSSV: 2100XXXXXX', { noIndent: true, align: AlignmentType.LEFT }),
    p('Giảng viên hướng dẫn: ThS. Nguyễn Văn B', { noIndent: true, align: AlignmentType.LEFT }),
    empty(), empty(), empty(), empty(),
    center('CẦN THƠ, NĂM 2025', SZ, true),
  ]
};

// ======================== ACKNOWLEDGMENTS ========================
const acknowledgments = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('LỜI CẢM ƠN', 28, true), empty(),
    p('Trong suốt quá trình thực hiện tiểu luận tốt nghiệp, em đã nhận được rất nhiều sự giúp đỡ và hỗ trợ từ quý thầy cô, gia đình và bạn bè. Em xin gửi lời cảm ơn chân thành đến:'),
    p('Đầu tiên, em xin chân thành cảm ơn Ban Giám hiệu Trường Đại học Tây Đô, Khoa Kỹ thuật – Công nghệ đã tạo điều kiện thuận lợi cho em trong suốt quá trình học tập và nghiên cứu tại trường.'),
    p('Em xin bày tỏ lòng biết ơn sâu sắc đến giảng viên hướng dẫn – ThS. Nguyễn Văn B – người đã tận tình chỉ dẫn, góp ý và định hướng cho em trong suốt quá trình thực hiện đề tài. Những lời khuyên và sự hướng dẫn tận tâm của thầy/cô đã giúp em hoàn thành tiểu luận một cách tốt nhất.'),
    p('Em cũng xin gửi lời cảm ơn đến toàn thể quý thầy cô trong Khoa Kỹ thuật – Công nghệ đã truyền đạt cho em những kiến thức nền tảng quý báu trong suốt bốn năm học tập tại trường. Những kiến thức đó chính là nền tảng vững chắc giúp em hoàn thành được đề tài này.'),
    p('Cuối cùng, em xin gửi lời cảm ơn đến gia đình, bạn bè đã luôn động viên, khích lệ và hỗ trợ em trong suốt quá trình học tập cũng như thực hiện tiểu luận.'),
    p('Mặc dù đã cố gắng hết sức nhưng tiểu luận không thể tránh khỏi những thiếu sót. Em rất mong nhận được sự góp ý của quý thầy cô và bạn đọc để em có thể hoàn thiện hơn.'),
    empty(),
    p('Cần Thơ, ngày ... tháng ... năm 2025', { align: AlignmentType.RIGHT, noIndent: true }),
    p('Sinh viên thực hiện', { align: AlignmentType.RIGHT, noIndent: true, bold: true }),
    empty(), empty(),
    p('Nguyễn Văn A', { align: AlignmentType.RIGHT, noIndent: true, bold: true }),
  ]
};

// ======================== COMMITMENT ========================
const commitment = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('LỜI CAM ĐOAN', 28, true), empty(),
    p('Em xin cam đoan tiểu luận tốt nghiệp "Xây dựng website đặt phòng khách sạn trực tuyến sử dụng MERN Stack" là công trình nghiên cứu của riêng em dưới sự hướng dẫn của ThS. Nguyễn Văn B.'),
    p('Các số liệu, kết quả trình bày trong tiểu luận là trung thực và chưa từng được công bố trong bất kỳ công trình nghiên cứu nào khác.'),
    p('Các tài liệu tham khảo, trích dẫn trong tiểu luận đều được ghi rõ nguồn gốc. Nếu phát hiện có bất kỳ sự gian lận nào, em xin hoàn toàn chịu trách nhiệm về nội dung tiểu luận của mình.'),
    empty(),
    p('Cần Thơ, ngày ... tháng ... năm 2025', { align: AlignmentType.RIGHT, noIndent: true }),
    p('Sinh viên thực hiện', { align: AlignmentType.RIGHT, noIndent: true, bold: true }),
    empty(), empty(),
    p('Nguyễn Văn A', { align: AlignmentType.RIGHT, noIndent: true, bold: true }),
  ]
};

// ======================== ABSTRACT ========================
const abstractPage = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('TÓM TẮT', 28, true), empty(),
    p('Trong bối cảnh chuyển đổi số đang diễn ra mạnh mẽ, ngành du lịch và khách sạn cần ứng dụng công nghệ thông tin để nâng cao chất lượng dịch vụ và trải nghiệm khách hàng. Tiểu luận này trình bày quá trình phân tích, thiết kế và xây dựng một website đặt phòng khách sạn trực tuyến sử dụng bộ công nghệ MERN Stack (MongoDB, Express.js, React.js, Node.js).'),
    p('Hệ thống được xây dựng với các chức năng chính bao gồm: quản lý thông tin khách sạn và phòng, tìm kiếm và lọc khách sạn theo nhiều tiêu chí, đặt phòng trực tuyến với tích hợp cổng thanh toán VNPay và MoMo, hệ thống đánh giá và nhận xét, chatbot hỗ trợ tư vấn sử dụng trí tuệ nhân tạo Google Gemini, quản lý mã giảm giá, hệ thống thông báo thời gian thực qua Socket.IO, và trang quản trị cho admin.'),
    p('Kết quả đạt được là một hệ thống web hoàn chỉnh với giao diện thân thiện, tương thích đa thiết bị (responsive design), hiệu suất tốt và đáp ứng đầy đủ các yêu cầu nghiệp vụ của một hệ thống đặt phòng khách sạn trực tuyến. Hệ thống đã được kiểm thử với nhiều kịch bản khác nhau, cho kết quả hoạt động ổn định và chính xác.'),
    empty(),
    p('Từ khóa: đặt phòng khách sạn, MERN Stack, React.js, Node.js, MongoDB, Socket.IO, VNPay, MoMo.', { italic: true }),
    pageBreak(),
    center('ABSTRACT', 28, true), empty(),
    p('In the context of the strong digital transformation, the tourism and hotel industry needs to apply information technology to improve service quality and customer experience. This thesis presents the process of analysis, design, and development of an online hotel booking website using the MERN Stack technology (MongoDB, Express.js, React.js, Node.js).', { noIndent: true }),
    p('The system is built with main functions including: hotel and room information management, hotel search and filtering by multiple criteria, online booking with VNPay and MoMo payment gateway integration, review and rating system, AI-powered chatbot using Google Gemini, coupon management, real-time notification system via Socket.IO, and admin dashboard.', { noIndent: true }),
    p('The result is a complete web system with a user-friendly interface, responsive design, good performance, and fully meeting the business requirements of an online hotel booking system. The system has been tested with various scenarios, showing stable and accurate operation.', { noIndent: true }),
    empty(),
    p('Keywords: hotel booking, MERN Stack, React.js, Node.js, MongoDB, Socket.IO, VNPay, MoMo.', { italic: true, noIndent: true }),
  ]
};

// ======================== TABLE OF CONTENTS (placeholder) ========================
const tocPage = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('MỤC LỤC', 28, true), empty(),
    p('(Mục lục sẽ được tạo tự động trong Microsoft Word: References → Table of Contents)', { italic: true, noIndent: true }),
    empty(),
    p('LỜI CẢM ƠN ..................................................... i', { noIndent: true }),
    p('LỜI CAM ĐOAN .................................................. ii', { noIndent: true }),
    p('TÓM TẮT ....................................................... iii', { noIndent: true }),
    p('MỤC LỤC ....................................................... iv', { noIndent: true }),
    p('DANH MỤC HÌNH ẢNH ............................................. vi', { noIndent: true }),
    p('DANH MỤC BẢNG BIỂU ............................................ vii', { noIndent: true }),
    p('DANH MỤC TỪ VIẾT TẮT .......................................... viii', { noIndent: true }),
    p('CHƯƠNG 1: TỔNG QUAN ............................................ 1', { noIndent: true }),
    p('  1.1. Đặt vấn đề .............................................. 1', { noIndent: true }),
    p('  1.2. Mục tiêu đề tài ......................................... 2', { noIndent: true }),
    p('  1.3. Phạm vi đề tài .......................................... 3', { noIndent: true }),
    p('  1.4. Phương pháp nghiên cứu .................................. 3', { noIndent: true }),
    p('  1.5. Kế hoạch thực hiện ...................................... 4', { noIndent: true }),
    p('CHƯƠNG 2: CƠ SỞ LÝ THUYẾT ..................................... 5', { noIndent: true }),
    p('  2.1. Tổng quan về MERN Stack .................................. 5', { noIndent: true }),
    p('  2.2. MongoDB .................................................. 6', { noIndent: true }),
    p('  2.3. Express.js ............................................... 8', { noIndent: true }),
    p('  2.4. React.js ................................................. 9', { noIndent: true }),
    p('  2.5. Node.js .................................................. 11', { noIndent: true }),
    p('  2.6. Các công nghệ hỗ trợ .................................... 12', { noIndent: true }),
    p('  2.7. Hệ thống tham khảo ...................................... 15', { noIndent: true }),
    p('CHƯƠNG 3: PHÂN TÍCH VÀ THIẾT KẾ HỆ THỐNG ...................... 16', { noIndent: true }),
    p('  3.1. Phân tích yêu cầu ....................................... 16', { noIndent: true }),
    p('  3.2. Biểu đồ Use Case ........................................ 18', { noIndent: true }),
    p('  3.3. Thiết kế cơ sở dữ liệu .................................. 22', { noIndent: true }),
    p('  3.4. Thiết kế API ............................................. 28', { noIndent: true }),
    p('  3.5. Thiết kế giao diện ....................................... 30', { noIndent: true }),
    p('CHƯƠNG 4: KẾT QUẢ THỰC HIỆN .................................... 32', { noIndent: true }),
    p('  4.1. Giao diện người dùng ..................................... 32', { noIndent: true }),
    p('  4.2. Giao diện quản trị ....................................... 38', { noIndent: true }),
    p('  4.3. Kiểm thử hệ thống ....................................... 42', { noIndent: true }),
    p('CHƯƠNG 5: KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN ........................ 46', { noIndent: true }),
    p('  5.1. Kết luận ................................................. 46', { noIndent: true }),
    p('  5.2. Hạn chế .................................................. 47', { noIndent: true }),
    p('  5.3. Hướng phát triển ......................................... 47', { noIndent: true }),
    p('TÀI LIỆU THAM KHẢO ............................................. 48', { noIndent: true }),
    p('PHỤ LỤC ........................................................ 50', { noIndent: true }),
    pageBreak(),
    center('DANH MỤC HÌNH ẢNH', 28, true), empty(),
    p('Hình 3.1. Biểu đồ Use Case tổng quát ........................... 18', { noIndent: true }),
    p('Hình 3.2. Biểu đồ Use Case – Quản lý đặt phòng ................ 19', { noIndent: true }),
    p('Hình 3.3. Biểu đồ ERD .......................................... 22', { noIndent: true }),
    p('Hình 3.4. Sơ đồ kiến trúc hệ thống ............................. 30', { noIndent: true }),
    p('Hình 4.1. Trang chủ ............................................. 32', { noIndent: true }),
    p('Hình 4.2. Trang danh sách khách sạn ............................. 33', { noIndent: true }),
    p('Hình 4.3. Trang chi tiết khách sạn .............................. 34', { noIndent: true }),
    p('Hình 4.4. Trang đặt phòng ....................................... 35', { noIndent: true }),
    p('Hình 4.5. Trang thanh toán ...................................... 36', { noIndent: true }),
    p('Hình 4.6. Trang xác nhận đặt phòng .............................. 37', { noIndent: true }),
    p('Hình 4.7. Chatbot hỗ trợ ........................................ 37', { noIndent: true }),
    p('Hình 4.8. Dashboard admin ........................................ 38', { noIndent: true }),
    p('Hình 4.9. Quản lý khách sạn ..................................... 39', { noIndent: true }),
    p('Hình 4.10. Quản lý đặt phòng .................................... 40', { noIndent: true }),
    pageBreak(),
    center('DANH MỤC BẢNG BIỂU', 28, true), empty(),
    p('Bảng 1.1. Kế hoạch thực hiện .................................... 4', { noIndent: true }),
    p('Bảng 3.1. Danh sách các actor ................................... 17', { noIndent: true }),
    p('Bảng 3.2. Đặc tả Use Case – Đăng ký ............................ 19', { noIndent: true }),
    p('Bảng 3.3. Đặc tả Use Case – Đặt phòng .......................... 20', { noIndent: true }),
    p('Bảng 3.4. Đặc tả Use Case – Thanh toán .......................... 21', { noIndent: true }),
    p('Bảng 3.5. Cấu trúc collection User .............................. 23', { noIndent: true }),
    p('Bảng 3.6. Cấu trúc collection Hotel ............................. 24', { noIndent: true }),
    p('Bảng 3.7. Cấu trúc collection Room .............................. 25', { noIndent: true }),
    p('Bảng 3.8. Cấu trúc collection Booking ........................... 26', { noIndent: true }),
    p('Bảng 3.9. Cấu trúc collection Payment ........................... 27', { noIndent: true }),
    p('Bảng 3.10. Danh sách API endpoints ............................... 28', { noIndent: true }),
    p('Bảng 4.1. Kết quả kiểm thử chức năng ............................ 42', { noIndent: true }),
    p('Bảng 4.2. Kết quả kiểm thử hiệu suất ........................... 44', { noIndent: true }),
    pageBreak(),
    center('DANH MỤC TỪ VIẾT TẮT', 28, true), empty(),
    makeTable(['STT', 'Từ viết tắt', 'Ý nghĩa'], [
      ['1', 'API', 'Application Programming Interface'],
      ['2', 'CRUD', 'Create, Read, Update, Delete'],
      ['3', 'CSS', 'Cascading Style Sheets'],
      ['4', 'DOM', 'Document Object Model'],
      ['5', 'ERD', 'Entity Relationship Diagram'],
      ['6', 'HTML', 'HyperText Markup Language'],
      ['7', 'HTTP', 'HyperText Transfer Protocol'],
      ['8', 'JSON', 'JavaScript Object Notation'],
      ['9', 'JWT', 'JSON Web Token'],
      ['10', 'MERN', 'MongoDB, Express.js, React.js, Node.js'],
      ['11', 'MVC', 'Model-View-Controller'],
      ['12', 'NoSQL', 'Not Only SQL'],
      ['13', 'REST', 'Representational State Transfer'],
      ['14', 'SPA', 'Single Page Application'],
      ['15', 'UI/UX', 'User Interface / User Experience'],
    ]),
  ]
};

// ======================== CHAPTER 1 ========================
const chapter1 = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('CHƯƠNG 1', 28, true),
    center('TỔNG QUAN', 28, true), empty(),
    h2('1.1. Đặt vấn đề'),
    p('Trong những năm gần đây, sự phát triển mạnh mẽ của Internet và công nghệ thông tin đã tạo ra những thay đổi to lớn trong nhiều lĩnh vực của đời sống xã hội, đặc biệt là trong ngành du lịch và dịch vụ khách sạn. Theo thống kê của Bộ Văn hóa, Thể thao và Du lịch, năm 2023 Việt Nam đón hơn 12.6 triệu lượt khách quốc tế và khoảng 108 triệu lượt khách nội địa, cho thấy nhu cầu về dịch vụ lưu trú là rất lớn.'),
    p('Tuy nhiên, việc đặt phòng khách sạn tại Việt Nam hiện nay vẫn còn nhiều bất cập. Nhiều khách sạn vừa và nhỏ chưa có hệ thống đặt phòng trực tuyến riêng, phải phụ thuộc vào các nền tảng trung gian như Booking.com, Agoda hay Traveloka với mức phí hoa hồng từ 15-25% trên mỗi đơn đặt phòng. Điều này làm giảm đáng kể lợi nhuận của các cơ sở lưu trú.'),
    p('Bên cạnh đó, người dùng cũng gặp nhiều khó khăn khi phải so sánh giá trên nhiều nền tảng khác nhau, thiếu thông tin chi tiết về phòng ở, và không có kênh hỗ trợ tư vấn nhanh chóng. Quy trình đặt phòng truyền thống qua điện thoại hay email cũng tốn nhiều thời gian và dễ xảy ra sai sót.'),
    p('Xuất phát từ thực trạng trên, việc xây dựng một website đặt phòng khách sạn trực tuyến riêng, với đầy đủ tính năng hiện đại, giao diện thân thiện và chi phí vận hành thấp là một nhu cầu cấp thiết. Hệ thống này không chỉ giúp các khách sạn tiết kiệm chi phí hoa hồng cho bên thứ ba mà còn nâng cao trải nghiệm người dùng thông qua các tính năng như chatbot AI hỗ trợ, thanh toán đa dạng và thông báo thời gian thực.'),
    p('Với sự phát triển mạnh mẽ của JavaScript và bộ công nghệ MERN Stack (MongoDB, Express.js, React.js, Node.js), việc xây dựng một ứng dụng web full-stack hiệu quả và hiện đại trở nên khả thi hơn bao giờ hết. MERN Stack cho phép sử dụng một ngôn ngữ duy nhất (JavaScript) cho cả frontend và backend, giảm thiểu độ phức tạp và tăng năng suất phát triển.'),
    empty(),
    h2('1.2. Mục tiêu đề tài'),
    h3('1.2.1. Mục tiêu chung'),
    p('Xây dựng hoàn chỉnh một website đặt phòng khách sạn trực tuyến sử dụng bộ công nghệ MERN Stack, đáp ứng đầy đủ các yêu cầu nghiệp vụ của một hệ thống thương mại điện tử trong lĩnh vực khách sạn – du lịch.'),
    h3('1.2.2. Mục tiêu cụ thể'),
    bullet('Phân tích và thiết kế hệ thống đặt phòng khách sạn trực tuyến với đầy đủ các chức năng cần thiết.'),
    bullet('Xây dựng giao diện người dùng (frontend) sử dụng React.js kết hợp Tailwind CSS, đảm bảo tương thích đa thiết bị (responsive design).'),
    bullet('Phát triển phần backend sử dụng Node.js và Express.js với kiến trúc RESTful API.'),
    bullet('Thiết kế và triển khai cơ sở dữ liệu NoSQL với MongoDB, tối ưu cho dữ liệu phi cấu trúc.'),
    bullet('Tích hợp các cổng thanh toán trực tuyến VNPay và MoMo.'),
    bullet('Xây dựng chatbot hỗ trợ tư vấn sử dụng trí tuệ nhân tạo Google Gemini API.'),
    bullet('Triển khai hệ thống thông báo thời gian thực sử dụng Socket.IO.'),
    bullet('Xây dựng trang quản trị (admin panel) để quản lý toàn bộ hệ thống.'),
    bullet('Kiểm thử và đánh giá hiệu suất hệ thống.'),
    empty(),
    h2('1.3. Phạm vi đề tài'),
    h3('1.3.1. Phạm vi nghiên cứu'),
    bullet('Nghiên cứu bộ công nghệ MERN Stack và các thư viện liên quan.'),
    bullet('Nghiên cứu quy trình đặt phòng khách sạn trực tuyến.'),
    bullet('Nghiên cứu tích hợp cổng thanh toán VNPay, MoMo.'),
    bullet('Nghiên cứu ứng dụng AI (Google Gemini) trong hỗ trợ khách hàng.'),
    h3('1.3.2. Phạm vi ứng dụng'),
    bullet('Hệ thống phục vụ cho các khách sạn vừa và nhỏ tại Việt Nam.'),
    bullet('Người dùng cuối: khách hàng có nhu cầu đặt phòng khách sạn.'),
    bullet('Quản trị viên: nhân viên quản lý khách sạn.'),
    h3('1.3.3. Giới hạn đề tài'),
    bullet('Chưa triển khai trên môi trường production (cloud hosting).'),
    bullet('Chưa hỗ trợ đa ngôn ngữ (chỉ tiếng Việt).'),
    bullet('Chưa tích hợp bản đồ hiển thị vị trí khách sạn.'),
    bullet('Thanh toán chạy ở chế độ sandbox/test.'),
    empty(),
    h2('1.4. Phương pháp nghiên cứu'),
    bullet('Phương pháp nghiên cứu tài liệu: Thu thập, đọc và phân tích các tài liệu liên quan đến MERN Stack, RESTful API, Socket.IO, thanh toán trực tuyến, AI chatbot.'),
    bullet('Phương pháp phân tích và thiết kế hệ thống: Sử dụng UML để mô hình hóa hệ thống (Use Case Diagram, Sequence Diagram, ERD).'),
    bullet('Phương pháp thực nghiệm: Xây dựng hệ thống prototype, kiểm thử chức năng và hiệu suất.'),
    bullet('Phương pháp so sánh: So sánh với các hệ thống đặt phòng hiện có để đánh giá ưu nhược điểm.'),
    empty(),
    h2('1.5. Kế hoạch thực hiện'),
    makeTable(['Giai đoạn', 'Nội dung công việc', 'Thời gian'], [
      ['1', 'Tìm hiểu yêu cầu, nghiên cứu công nghệ', 'Tuần 1-2'],
      ['2', 'Phân tích và thiết kế hệ thống', 'Tuần 3-4'],
      ['3', 'Xây dựng cơ sở dữ liệu và Backend API', 'Tuần 5-7'],
      ['4', 'Xây dựng giao diện Frontend', 'Tuần 8-10'],
      ['5', 'Tích hợp thanh toán, chatbot, Socket.IO', 'Tuần 11-12'],
      ['6', 'Kiểm thử và sửa lỗi', 'Tuần 13-14'],
      ['7', 'Viết báo cáo, hoàn thiện tiểu luận', 'Tuần 15-16'],
    ]),
    p('Bảng 1.1. Kế hoạch thực hiện đề tài', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
  ]
};

// ======================== CHAPTER 2 ========================
const chapter2 = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('CHƯƠNG 2', 28, true),
    center('CƠ SỞ LÝ THUYẾT', 28, true), empty(),
    h2('2.1. Tổng quan về MERN Stack'),
    p('MERN Stack là một bộ công nghệ phát triển web full-stack dựa trên JavaScript, bao gồm bốn thành phần chính: MongoDB (cơ sở dữ liệu), Express.js (framework phía server), React.js (thư viện giao diện phía client) và Node.js (môi trường runtime). MERN Stack cho phép nhà phát triển sử dụng một ngôn ngữ lập trình duy nhất (JavaScript/TypeScript) cho cả frontend lẫn backend, giúp giảm thiểu chi phí học tập và tăng hiệu suất làm việc nhóm.'),
    p('Ưu điểm chính của MERN Stack bao gồm: (1) Sử dụng JavaScript xuyên suốt giúp dễ dàng chia sẻ code giữa client và server; (2) MongoDB linh hoạt với dữ liệu JSON-like phù hợp cho ứng dụng web hiện đại; (3) React.js với Virtual DOM cho hiệu suất render cao; (4) Node.js với mô hình event-driven, non-blocking I/O xử lý tốt nhiều kết nối đồng thời; (5) Hệ sinh thái npm phong phú với hàng triệu package hỗ trợ.'),
    p('Kiến trúc MERN Stack hoạt động theo mô hình client-server: React.js ở phía client gửi HTTP request đến Express.js/Node.js server thông qua RESTful API, server xử lý logic nghiệp vụ và tương tác với MongoDB để đọc/ghi dữ liệu, sau đó trả về response dạng JSON cho client hiển thị.'),
    empty(),
    h2('2.2. MongoDB'),
    h3('2.2.1. Giới thiệu'),
    p('MongoDB là một hệ quản trị cơ sở dữ liệu NoSQL mã nguồn mở, lưu trữ dữ liệu dưới dạng document (tài liệu) với định dạng BSON (Binary JSON). Khác với cơ sở dữ liệu quan hệ truyền thống sử dụng bảng và hàng, MongoDB tổ chức dữ liệu thành các collection chứa nhiều document, mỗi document có thể có cấu trúc khác nhau (schema-less).'),
    h3('2.2.2. Đặc điểm nổi bật'),
    bullet('Schema linh hoạt (Flexible Schema): Không yêu cầu định nghĩa cấu trúc cứng nhắc trước, cho phép dễ dàng thay đổi cấu trúc dữ liệu khi yêu cầu thay đổi.'),
    bullet('Khả năng mở rộng ngang (Horizontal Scaling): Hỗ trợ sharding để phân tán dữ liệu trên nhiều server, xử lý được lượng dữ liệu lớn.'),
    bullet('Hiệu suất cao: Hỗ trợ indexing đa dạng, aggregation pipeline mạnh mẽ, và in-memory storage engine.'),
    bullet('Replication: Hỗ trợ replica set đảm bảo tính sẵn sàng cao (high availability) và khả năng phục hồi dữ liệu.'),
    h3('2.2.3. Mongoose ODM'),
    p('Trong dự án này, Mongoose được sử dụng như một Object Document Mapper (ODM) cho MongoDB. Mongoose cung cấp một schema-based solution để mô hình hóa dữ liệu ứng dụng, bao gồm: built-in type casting, validation, query building, và business logic hooks (middleware). Mongoose giúp làm việc với MongoDB trở nên có cấu trúc và dễ quản lý hơn trong môi trường Node.js.'),
    empty(),
    h2('2.3. Express.js'),
    h3('2.3.1. Giới thiệu'),
    p('Express.js là một web application framework nhẹ và linh hoạt cho Node.js, cung cấp một bộ tính năng mạnh mẽ để xây dựng các ứng dụng web và API. Express.js là framework phổ biến nhất trong hệ sinh thái Node.js với hơn 60,000 stars trên GitHub và hàng triệu lượt tải xuống hàng tuần trên npm.'),
    h3('2.3.2. Đặc điểm chính'),
    bullet('Middleware system: Cho phép xử lý request qua nhiều lớp trung gian (authentication, logging, error handling, etc.).'),
    bullet('Routing mạnh mẽ: Hỗ trợ định tuyến linh hoạt với parameters, query strings, và route groups.'),
    bullet('Template engine: Hỗ trợ nhiều template engine (Pug, EJS, Handlebars).'),
    bullet('Static files: Dễ dàng phục vụ các file tĩnh (hình ảnh, CSS, JavaScript).'),
    h3('2.3.3. RESTful API'),
    p('REST (Representational State Transfer) là một kiến trúc phần mềm cho hệ thống phân tán, sử dụng các phương thức HTTP (GET, POST, PUT, DELETE) để thao tác với resources. Trong dự án này, Express.js được sử dụng để xây dựng RESTful API cho phép frontend React.js giao tiếp với backend một cách nhất quán và có cấu trúc.'),
    empty(),
    h2('2.4. React.js'),
    h3('2.4.1. Giới thiệu'),
    p('React.js là một thư viện JavaScript mã nguồn mở được phát triển bởi Facebook (Meta) để xây dựng giao diện người dùng (User Interface). React sử dụng kiến trúc component-based, cho phép chia giao diện thành các thành phần nhỏ, độc lập và có thể tái sử dụng. React là thư viện frontend phổ biến nhất hiện nay với hơn 200,000 stars trên GitHub.'),
    h3('2.4.2. Các khái niệm quan trọng'),
    bullet('Virtual DOM: React sử dụng Virtual DOM – một bản sao nhẹ của DOM thật – để tối ưu hóa việc cập nhật giao diện. Khi state thay đổi, React so sánh Virtual DOM mới và cũ (diffing algorithm), chỉ cập nhật những phần thay đổi trên DOM thật.'),
    bullet('JSX (JavaScript XML): Cú pháp mở rộng cho phép viết HTML trong JavaScript, giúp code trực quan và dễ đọc hơn.'),
    bullet('Components: Là đơn vị cơ bản trong React, chia thành Function Component (hiện đại, sử dụng Hooks) và Class Component (cũ hơn).'),
    bullet('Hooks: useState, useEffect, useContext, useMemo, useCallback... cho phép sử dụng state và lifecycle trong function component.'),
    bullet('Props: Cơ chế truyền dữ liệu từ component cha sang component con (one-way data flow).'),
    h3('2.4.3. Redux Toolkit và RTK Query'),
    p('Redux Toolkit (RTK) là bộ công cụ chính thức để quản lý state trong ứng dụng React. RTK đơn giản hóa việc cấu hình Redux store, tạo reducers và actions. RTK Query là một data fetching và caching solution tích hợp sẵn trong Redux Toolkit, tự động quản lý loading states, caching, và re-fetching, giảm đáng kể boilerplate code so với việc sử dụng useEffect + fetch thông thường.'),
    h3('2.4.4. React Router'),
    p('React Router là thư viện định tuyến phổ biến nhất cho React, cho phép xây dựng Single Page Application (SPA) với nhiều "trang" mà không cần tải lại trình duyệt. Trong dự án này sử dụng React Router v6 với các tính năng: nested routes, route protection, lazy loading.'),
    empty(),
    h2('2.5. Node.js'),
    h3('2.5.1. Giới thiệu'),
    p('Node.js là một môi trường runtime JavaScript được xây dựng trên Chrome V8 JavaScript Engine, cho phép chạy JavaScript ở phía server. Node.js sử dụng mô hình event-driven, non-blocking I/O, giúp xử lý hiệu quả nhiều kết nối đồng thời mà không cần tạo thread mới cho mỗi request (khác với mô hình thread-per-request truyền thống).'),
    h3('2.5.2. Đặc điểm'),
    bullet('Event Loop: Cơ chế xử lý bất đồng bộ (asynchronous) cho phép Node.js xử lý hàng nghìn kết nối đồng thời trên một thread duy nhất.'),
    bullet('npm (Node Package Manager): Hệ sinh thái package lớn nhất thế giới với hơn 2 triệu packages.'),
    bullet('Cross-platform: Chạy trên nhiều hệ điều hành (Windows, macOS, Linux).'),
    bullet('Streaming: Hỗ trợ xử lý dữ liệu dạng stream, hiệu quả cho file upload/download.'),
    h3('2.5.3. Ứng dụng trong dự án'),
    p('Trong dự án này, Node.js được sử dụng làm nền tảng cho backend server, kết hợp với Express.js để xử lý HTTP requests, Socket.IO cho real-time communication, và các package khác như jsonwebtoken (JWT authentication), bcryptjs (password hashing), multer (file upload), nodemailer (email sending).'),
    empty(),
    h2('2.6. Các công nghệ hỗ trợ'),
    h3('2.6.1. Tailwind CSS'),
    p('Tailwind CSS là một utility-first CSS framework cho phép xây dựng giao diện trực tiếp trong HTML/JSX bằng các class tiện ích (utility classes) thay vì viết CSS tùy chỉnh. Ưu điểm của Tailwind bao gồm: tốc độ phát triển nhanh, file CSS nhỏ (nhờ purge unused styles), dễ tùy chỉnh thông qua configuration, và hỗ trợ responsive design tốt với breakpoint prefixes (sm:, md:, lg:, xl:).'),
    h3('2.6.2. Socket.IO'),
    p('Socket.IO là một thư viện cho phép giao tiếp hai chiều (bidirectional) thời gian thực giữa client và server. Socket.IO xây dựng trên WebSocket protocol nhưng cung cấp thêm các tính năng: automatic reconnection, room/namespace support, broadcasting, và fallback mechanisms (long-polling) khi WebSocket không khả dụng. Trong dự án, Socket.IO được sử dụng cho hệ thống thông báo real-time (đặt phòng mới, thay đổi trạng thái).'),
    h3('2.6.3. JSON Web Token (JWT)'),
    p('JWT là một tiêu chuẩn mở (RFC 7519) để truyền thông tin an toàn giữa các bên dưới dạng JSON object. JWT bao gồm ba phần: Header (thuật toán mã hóa), Payload (dữ liệu), và Signature (chữ ký xác thực). Trong dự án sử dụng dual-token strategy: Access Token (thời hạn ngắn, 1 ngày) để xác thực request, và Refresh Token (thời hạn dài, 7 ngày) để tự động gia hạn access token mà không cần đăng nhập lại.'),
    h3('2.6.4. Cloudinary'),
    p('Cloudinary là một dịch vụ quản lý media (hình ảnh, video) trên cloud, cung cấp API để upload, lưu trữ, transform và deliver media. Trong dự án, Cloudinary được sử dụng để lưu trữ hình ảnh khách sạn, phòng, avatar người dùng và hình ảnh bài viết. Ưu điểm: CDN toàn cầu cho tốc độ tải nhanh, hỗ trợ resize/crop tự động, và API đơn giản.'),
    h3('2.6.5. Cổng thanh toán VNPay và MoMo'),
    p('VNPay là cổng thanh toán trực tuyến phổ biến tại Việt Nam, hỗ trợ thanh toán qua thẻ ATM nội địa, thẻ quốc tế (Visa, Master, JCB), ví VNPay QR. MoMo là ví điện tử lớn nhất Việt Nam với hơn 30 triệu người dùng, hỗ trợ thanh toán QR code, chuyển tiền, và thanh toán hóa đơn. Việc tích hợp cả hai cổng thanh toán giúp đa dạng hóa phương thức thanh toán cho người dùng.'),
    h3('2.6.6. Google Gemini API'),
    p('Google Gemini là mô hình AI đa phương thức mới nhất của Google, có khả năng hiểu và xử lý text, image, audio, video. Trong dự án, Gemini API (model gemini-2.0-flash) được sử dụng để xây dựng chatbot tư vấn khách hàng, hỗ trợ trả lời các câu hỏi về khách sạn, phòng, chính sách đặt phòng, và gợi ý phù hợp dựa trên yêu cầu của khách hàng.'),
    h3('2.6.7. Vite'),
    p('Vite là một build tool thế hệ mới cho frontend development, cung cấp tốc độ khởi động server nhanh (nhờ native ES modules) và Hot Module Replacement (HMR) gần như tức thì. So với Create React App (sử dụng Webpack), Vite nhanh hơn 10-100x trong development mode và tạo bundle nhỏ hơn cho production.'),
    empty(),
    h2('2.7. Các hệ thống tham khảo'),
    h3('2.7.1. Booking.com'),
    p('Booking.com là nền tảng đặt phòng trực tuyến lớn nhất thế giới với hơn 28 triệu listings. Hệ thống cung cấp các tính năng: tìm kiếm nâng cao, so sánh giá, đánh giá từ khách hàng, hủy phòng miễn phí, chương trình khách hàng thân thiết (Genius). Điểm tham khảo: UX flow đặt phòng, hệ thống filter, cách hiển thị review.'),
    h3('2.7.2. Traveloka'),
    p('Traveloka là nền tảng du lịch hàng đầu Đông Nam Á, hỗ trợ đặt khách sạn, vé máy bay, hoạt động giải trí. Điểm tham khảo: tích hợp thanh toán đa dạng (phù hợp thị trường Việt Nam), giao diện tiếng Việt, chương trình mã giảm giá, push notification.'),
    h3('2.7.3. So sánh và định hướng'),
    p('Dựa trên việc phân tích các hệ thống trên, đề tài hướng đến xây dựng một hệ thống có giao diện hiện đại, quy trình đặt phòng đơn giản, tích hợp thanh toán phù hợp thị trường Việt Nam (VNPay, MoMo), và bổ sung chatbot AI – một tính năng chưa phổ biến trong các hệ thống nhỏ.'),
  ]
};

// ======================== CHAPTER 3 ========================
const chapter3 = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('CHƯƠNG 3', 28, true),
    center('PHÂN TÍCH VÀ THIẾT KẾ HỆ THỐNG', 28, true), empty(),
    h2('3.1. Phân tích yêu cầu'),
    h3('3.1.1. Yêu cầu chức năng'),
    p('Dựa trên việc khảo sát các hệ thống đặt phòng hiện có và phân tích nhu cầu thực tế, hệ thống cần đáp ứng các yêu cầu chức năng sau:'),
    p('Đối với khách hàng (Guest/User):', { bold: true }),
    bullet('Đăng ký tài khoản, đăng nhập, quên mật khẩu, đổi mật khẩu.'),
    bullet('Tìm kiếm khách sạn theo địa điểm, ngày nhận/trả phòng, số khách, khoảng giá.'),
    bullet('Xem chi tiết thông tin khách sạn: hình ảnh, mô tả, tiện nghi, đánh giá.'),
    bullet('Xem danh sách phòng trống và thông tin chi tiết từng phòng.'),
    bullet('Đặt phòng trực tuyến với khả năng chọn nhiều phòng.'),
    bullet('Áp dụng mã giảm giá (coupon) khi đặt phòng.'),
    bullet('Thanh toán trực tuyến qua VNPay hoặc MoMo.'),
    bullet('Xem lịch sử đặt phòng, hủy phòng (theo chính sách).'),
    bullet('Đánh giá và nhận xét khách sạn sau khi check-out.'),
    bullet('Sử dụng chatbot AI để được tư vấn.'),
    bullet('Nhận thông báo real-time về trạng thái đặt phòng.'),
    bullet('Quản lý thông tin cá nhân, cập nhật avatar.'),
    bullet('Tra cứu đặt phòng bằng mã booking.'),
    p('Đối với quản trị viên (Admin):', { bold: true }),
    bullet('Quản lý khách sạn (CRUD): thêm, sửa, xóa, xem danh sách.'),
    bullet('Quản lý phòng (CRUD): thêm phòng vào khách sạn, cập nhật giá, trạng thái.'),
    bullet('Quản lý đặt phòng: xác nhận, từ chối, check-in, check-out.'),
    bullet('Quản lý người dùng: xem danh sách, khóa/mở khóa tài khoản.'),
    bullet('Quản lý đánh giá: phê duyệt, ẩn review vi phạm.'),
    bullet('Quản lý mã giảm giá: tạo, sửa, xóa coupon.'),
    bullet('Quản lý nội dung: bài viết, banner trang chủ.'),
    bullet('Thống kê doanh thu, lượt đặt phòng, đánh giá.'),
    bullet('Nhận thông báo real-time khi có đặt phòng mới.'),
    h3('3.1.2. Yêu cầu phi chức năng'),
    bullet('Hiệu suất: Thời gian phản hồi API < 500ms cho 95% request.'),
    bullet('Bảo mật: Mã hóa mật khẩu (bcrypt), JWT authentication, rate limiting, input validation.'),
    bullet('Khả năng mở rộng: Kiến trúc modular, dễ thêm tính năng mới.'),
    bullet('Tương thích: Hoạt động tốt trên các trình duyệt phổ biến (Chrome, Firefox, Safari, Edge).'),
    bullet('Responsive: Tương thích với desktop, tablet, mobile.'),
    bullet('Khả dụng: Uptime > 99% (khi deploy production).'),
    empty(),
    h2('3.2. Biểu đồ Use Case'),
    h3('3.2.1. Xác định Actor'),
    makeTable(['Actor', 'Mô tả'], [
      ['Guest (Khách)', 'Người dùng chưa đăng nhập, có thể xem thông tin và tìm kiếm'],
      ['User (Người dùng)', 'Khách hàng đã đăng nhập, có thể đặt phòng, thanh toán, đánh giá'],
      ['Admin (Quản trị viên)', 'Người quản lý hệ thống, có toàn quyền quản trị'],
      ['Payment Gateway', 'Hệ thống thanh toán bên ngoài (VNPay, MoMo)'],
      ['Gemini AI', 'Dịch vụ AI bên ngoài cung cấp khả năng chatbot'],
    ]),
    p('Bảng 3.1. Danh sách các Actor trong hệ thống', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    h3('3.2.2. Đặc tả Use Case'),
    p('Use Case: Đăng ký tài khoản', { bold: true }),
    makeTable(['Thành phần', 'Mô tả'], [
      ['Tên Use Case', 'Đăng ký tài khoản'],
      ['Actor', 'Guest'],
      ['Mô tả', 'Người dùng tạo tài khoản mới để sử dụng hệ thống'],
      ['Điều kiện tiên quyết', 'Người dùng chưa có tài khoản'],
      ['Luồng chính', '1. Guest truy cập trang đăng ký\n2. Nhập họ tên, email, mật khẩu, xác nhận mật khẩu\n3. Nhấn nút Đăng ký\n4. Hệ thống validate thông tin\n5. Tạo tài khoản thành công\n6. Chuyển đến trang đăng nhập'],
      ['Luồng ngoại lệ', 'Email đã tồn tại: hiển thị thông báo lỗi\nMật khẩu không khớp: hiển thị lỗi validation'],
      ['Điều kiện sau', 'Tài khoản mới được tạo trong database'],
    ]),
    p('Bảng 3.2. Đặc tả Use Case – Đăng ký tài khoản', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    p('Use Case: Đặt phòng', { bold: true }),
    makeTable(['Thành phần', 'Mô tả'], [
      ['Tên Use Case', 'Đặt phòng khách sạn'],
      ['Actor', 'User'],
      ['Mô tả', 'Người dùng thực hiện đặt phòng khách sạn trực tuyến'],
      ['Điều kiện tiên quyết', 'Người dùng đã đăng nhập, phòng còn trống'],
      ['Luồng chính', '1. User chọn khách sạn và phòng\n2. Chọn ngày nhận/trả phòng\n3. Nhập thông tin khách\n4. Áp dụng mã giảm giá (tùy chọn)\n5. Xác nhận thông tin đặt phòng\n6. Chọn phương thức thanh toán\n7. Thực hiện thanh toán\n8. Nhận xác nhận đặt phòng thành công'],
      ['Luồng ngoại lệ', 'Phòng hết: thông báo hết phòng\nThanh toán thất bại: thông báo lỗi, cho phép thử lại\nMã giảm giá không hợp lệ: thông báo lỗi'],
      ['Điều kiện sau', 'Booking được tạo với trạng thái confirmed, Payment record được tạo'],
    ]),
    p('Bảng 3.3. Đặc tả Use Case – Đặt phòng', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    p('Use Case: Thanh toán trực tuyến', { bold: true }),
    makeTable(['Thành phần', 'Mô tả'], [
      ['Tên Use Case', 'Thanh toán trực tuyến'],
      ['Actor', 'User, Payment Gateway'],
      ['Mô tả', 'Xử lý thanh toán đặt phòng qua VNPay hoặc MoMo'],
      ['Điều kiện tiên quyết', 'User đã xác nhận thông tin đặt phòng'],
      ['Luồng chính', '1. User chọn phương thức thanh toán (VNPay/MoMo)\n2. Hệ thống tạo URL thanh toán\n3. Redirect user đến trang thanh toán gateway\n4. User hoàn tất thanh toán trên gateway\n5. Gateway callback về hệ thống\n6. Hệ thống verify và cập nhật trạng thái\n7. Hiển thị kết quả thanh toán'],
      ['Luồng ngoại lệ', 'Timeout: hủy giao dịch\nUser hủy: quay về trang đặt phòng\nLỗi gateway: thông báo thử lại sau'],
      ['Điều kiện sau', 'Payment status = completed, Booking status = confirmed'],
    ]),
    p('Bảng 3.4. Đặc tả Use Case – Thanh toán trực tuyến', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    h2('3.3. Thiết kế cơ sở dữ liệu'),
    h3('3.3.1. Mô hình dữ liệu'),
    p('Hệ thống sử dụng MongoDB (NoSQL) với Mongoose ODM. Dữ liệu được tổ chức thành các collection chính sau: User, Hotel, Room, Booking, Payment, Review, Coupon, Article, Notification, SiteBanner, ContactMessage. Mỗi collection được thiết kế với schema phù hợp, có validation, indexes và references giữa các collection.'),
    empty(),
    h3('3.3.2. Cấu trúc các Collection'),
    p('Collection User:', { bold: true }),
    makeTable(['Trường', 'Kiểu dữ liệu', 'Mô tả', 'Ràng buộc'], [
      ['_id', 'ObjectId', 'ID tự động', 'Primary Key'],
      ['name', 'String', 'Họ tên người dùng', 'Required, trim'],
      ['email', 'String', 'Email đăng nhập', 'Required, unique, lowercase'],
      ['password', 'String', 'Mật khẩu (đã hash)', 'Required, minlength: 6'],
      ['phone', 'String', 'Số điện thoại', 'Optional'],
      ['avatar', 'String', 'URL ảnh đại diện', 'Default: avatar mặc định'],
      ['role', 'String', 'Vai trò', 'enum: [user, admin], default: user'],
      ['refreshToken', 'String', 'Token làm mới phiên', 'Optional'],
      ['resetPasswordToken', 'String', 'Token đặt lại mật khẩu', 'Optional'],
      ['resetPasswordExpires', 'Date', 'Hạn token reset', 'Optional'],
      ['createdAt', 'Date', 'Ngày tạo', 'Auto (timestamps)'],
    ]),
    p('Bảng 3.5. Cấu trúc collection User', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    p('Collection Hotel:', { bold: true }),
    makeTable(['Trường', 'Kiểu dữ liệu', 'Mô tả', 'Ràng buộc'], [
      ['_id', 'ObjectId', 'ID tự động', 'Primary Key'],
      ['name', 'String', 'Tên khách sạn', 'Required, trim'],
      ['description', 'String', 'Mô tả chi tiết', 'Required'],
      ['address', 'String', 'Địa chỉ', 'Required'],
      ['city', 'String', 'Thành phố', 'Required'],
      ['images', '[String]', 'Danh sách URL hình ảnh', 'Array of URLs'],
      ['amenities', '[String]', 'Tiện nghi', 'Array'],
      ['rating', 'Number', 'Điểm đánh giá trung bình', 'Default: 0, min: 0, max: 5'],
      ['reviewCount', 'Number', 'Số lượng đánh giá', 'Default: 0'],
      ['featured', 'Boolean', 'Khách sạn nổi bật', 'Default: false'],
      ['priceRange', 'Object', 'Khoảng giá {min, max}', 'Computed'],
      ['createdAt', 'Date', 'Ngày tạo', 'Auto'],
    ]),
    p('Bảng 3.6. Cấu trúc collection Hotel', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    p('Collection Room:', { bold: true }),
    makeTable(['Trường', 'Kiểu dữ liệu', 'Mô tả', 'Ràng buộc'], [
      ['_id', 'ObjectId', 'ID tự động', 'Primary Key'],
      ['hotel', 'ObjectId', 'Ref đến Hotel', 'Required, ref: Hotel'],
      ['name', 'String', 'Tên loại phòng', 'Required'],
      ['description', 'String', 'Mô tả phòng', 'Optional'],
      ['price', 'Number', 'Giá/đêm (VNĐ)', 'Required, min: 0'],
      ['capacity', 'Number', 'Sức chứa (người)', 'Required, min: 1'],
      ['quantity', 'Number', 'Số lượng phòng', 'Required, min: 1'],
      ['images', '[String]', 'Hình ảnh phòng', 'Array of URLs'],
      ['amenities', '[String]', 'Tiện nghi phòng', 'Array'],
      ['isAvailable', 'Boolean', 'Trạng thái khả dụng', 'Default: true'],
      ['createdAt', 'Date', 'Ngày tạo', 'Auto'],
    ]),
    p('Bảng 3.7. Cấu trúc collection Room', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    p('Collection Booking:', { bold: true }),
    makeTable(['Trường', 'Kiểu dữ liệu', 'Mô tả', 'Ràng buộc'], [
      ['_id', 'ObjectId', 'ID tự động', 'Primary Key'],
      ['user', 'ObjectId', 'Ref đến User', 'Required, ref: User'],
      ['hotel', 'ObjectId', 'Ref đến Hotel', 'Required, ref: Hotel'],
      ['rooms', '[Object]', 'DS phòng đặt {room, quantity}', 'Required'],
      ['checkIn', 'Date', 'Ngày nhận phòng', 'Required'],
      ['checkOut', 'Date', 'Ngày trả phòng', 'Required'],
      ['guests', 'Object', 'Thông tin khách {name, email, phone}', 'Required'],
      ['totalAmount', 'Number', 'Tổng tiền (VNĐ)', 'Required'],
      ['coupon', 'ObjectId', 'Mã giảm giá áp dụng', 'Optional, ref: Coupon'],
      ['discount', 'Number', 'Số tiền giảm', 'Default: 0'],
      ['status', 'String', 'Trạng thái đặt phòng', 'enum: [pending, confirmed, checked_in, checked_out, cancelled]'],
      ['bookingCode', 'String', 'Mã đặt phòng', 'Unique, auto-generated'],
      ['notes', 'String', 'Ghi chú', 'Optional'],
      ['createdAt', 'Date', 'Ngày tạo', 'Auto'],
    ]),
    p('Bảng 3.8. Cấu trúc collection Booking', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    p('Collection Payment:', { bold: true }),
    makeTable(['Trường', 'Kiểu dữ liệu', 'Mô tả', 'Ràng buộc'], [
      ['_id', 'ObjectId', 'ID tự động', 'Primary Key'],
      ['booking', 'ObjectId', 'Ref đến Booking', 'Required, ref: Booking'],
      ['user', 'ObjectId', 'Ref đến User', 'Required, ref: User'],
      ['amount', 'Number', 'Số tiền thanh toán', 'Required'],
      ['method', 'String', 'Phương thức', 'enum: [vnpay, momo]'],
      ['status', 'String', 'Trạng thái', 'enum: [pending, completed, failed, refunded]'],
      ['transactionId', 'String', 'Mã giao dịch gateway', 'Optional'],
      ['gatewayResponse', 'Object', 'Response từ gateway', 'Optional'],
      ['paidAt', 'Date', 'Thời điểm thanh toán', 'Optional'],
      ['createdAt', 'Date', 'Ngày tạo', 'Auto'],
    ]),
    p('Bảng 3.9. Cấu trúc collection Payment', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    h2('3.4. Thiết kế API'),
    h3('3.4.1. Danh sách API Endpoints'),
    p('Hệ thống sử dụng RESTful API với base URL: /api/v1. Dưới đây là danh sách các nhóm API chính:'),
    makeTable(['Nhóm', 'Method', 'Endpoint', 'Mô tả'], [
      ['Auth', 'POST', '/auth/register', 'Đăng ký tài khoản'],
      ['Auth', 'POST', '/auth/login', 'Đăng nhập'],
      ['Auth', 'POST', '/auth/refresh-token', 'Làm mới token'],
      ['Auth', 'POST', '/auth/forgot-password', 'Quên mật khẩu'],
      ['Auth', 'PUT', '/auth/reset-password/:token', 'Đặt lại mật khẩu'],
      ['Auth', 'GET', '/auth/me', 'Lấy thông tin cá nhân'],
      ['Hotels', 'GET', '/hotels', 'Danh sách khách sạn (filter, sort, paginate)'],
      ['Hotels', 'GET', '/hotels/:id', 'Chi tiết khách sạn'],
      ['Hotels', 'POST', '/hotels', 'Tạo khách sạn (Admin)'],
      ['Hotels', 'PUT', '/hotels/:id', 'Cập nhật khách sạn (Admin)'],
      ['Hotels', 'DELETE', '/hotels/:id', 'Xóa khách sạn (Admin)'],
      ['Rooms', 'GET', '/rooms/hotel/:hotelId', 'Phòng theo khách sạn'],
      ['Rooms', 'POST', '/rooms', 'Tạo phòng (Admin)'],
      ['Rooms', 'PUT', '/rooms/:id', 'Cập nhật phòng (Admin)'],
      ['Rooms', 'DELETE', '/rooms/:id', 'Xóa phòng (Admin)'],
      ['Bookings', 'POST', '/bookings', 'Tạo đặt phòng'],
      ['Bookings', 'GET', '/bookings/my', 'Lịch sử đặt phòng'],
      ['Bookings', 'GET', '/bookings/:id', 'Chi tiết booking'],
      ['Bookings', 'PUT', '/bookings/:id/cancel', 'Hủy đặt phòng'],
      ['Bookings', 'GET', '/bookings/lookup/:code', 'Tra cứu bằng mã'],
      ['Payments', 'POST', '/payments/vnpay/create', 'Tạo URL thanh toán VNPay'],
      ['Payments', 'GET', '/payments/vnpay/return', 'VNPay callback'],
      ['Payments', 'POST', '/payments/momo/create', 'Tạo URL thanh toán MoMo'],
      ['Payments', 'GET', '/payments/momo/return', 'MoMo callback'],
      ['Reviews', 'POST', '/reviews', 'Tạo đánh giá'],
      ['Reviews', 'GET', '/reviews/hotel/:hotelId', 'Reviews theo khách sạn'],
      ['Chatbot', 'POST', '/chatbot', 'Gửi tin nhắn chatbot'],
      ['Coupons', 'POST', '/coupons/validate', 'Kiểm tra mã giảm giá'],
      ['Admin', 'GET', '/admin/stats', 'Thống kê tổng quan'],
      ['Admin', 'GET', '/admin/bookings', 'Quản lý tất cả bookings'],
    ]),
    p('Bảng 3.10. Danh sách API Endpoints', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    h3('3.4.2. Xác thực và phân quyền'),
    p('Hệ thống sử dụng JWT (JSON Web Token) cho xác thực với chiến lược dual-token:'),
    bullet('Access Token: Gửi qua header Authorization: Bearer <token>, thời hạn 1 ngày.'),
    bullet('Refresh Token: Lưu trong httpOnly cookie, thời hạn 7 ngày, dùng để lấy access token mới.'),
    bullet('Middleware authMiddleware: Verify access token, gắn user info vào request object.'),
    bullet('Middleware adminMiddleware: Kiểm tra role === "admin" sau khi xác thực.'),
    bullet('Rate Limiting: Giới hạn số request/IP để chống brute force (login: 5 req/15min, general: 100 req/15min).'),
    empty(),
    h2('3.5. Thiết kế giao diện'),
    h3('3.5.1. Kiến trúc Frontend'),
    p('Frontend được xây dựng theo kiến trúc component-based với React.js, sử dụng các pattern:'),
    bullet('Feature-based folder structure: Mỗi tính năng (auth, bookings, hotels...) có thư mục riêng chứa API slice, components.'),
    bullet('Container/Presentational pattern: Tách logic (hooks, state) khỏi UI rendering.'),
    bullet('Custom Hooks: Tái sử dụng logic (useAuth, useDebounce, useSocket).'),
    bullet('Error Boundary: Bắt lỗi render để tránh crash toàn bộ app.'),
    bullet('Protected Route: Component bọc route yêu cầu đăng nhập hoặc quyền admin.'),
    h3('3.5.2. Cấu trúc thư mục Frontend'),
    p('src/', { noIndent: true }),
    p('├── app/ (Redux store configuration)', { noIndent: true }),
    p('├── components/ (Shared components: Navbar, Footer, Spinner...)', { noIndent: true }),
    p('├── features/ (Feature modules: auth, bookings, hotels...)', { noIndent: true }),
    p('├── hooks/ (Custom React hooks)', { noIndent: true }),
    p('├── pages/ (Page components mapped to routes)', { noIndent: true }),
    p('└── utils/ (Utility functions: format currency, date...)', { noIndent: true }),
    h3('3.5.3. Responsive Design'),
    p('Hệ thống sử dụng Tailwind CSS với mobile-first approach. Các breakpoint: sm (640px), md (768px), lg (1024px), xl (1280px). Giao diện được thiết kế tối ưu cho 3 nhóm thiết bị: mobile (< 768px), tablet (768px - 1024px), desktop (> 1024px).'),
  ]
};

// ======================== CHAPTER 4 ========================
const chapter4 = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('CHƯƠNG 4', 28, true),
    center('KẾT QUẢ THỰC HIỆN', 28, true), empty(),
    h2('4.1. Môi trường phát triển'),
    makeTable(['Thành phần', 'Công nghệ/Công cụ', 'Phiên bản'], [
      ['Hệ điều hành', 'Windows 11', '23H2'],
      ['IDE', 'Visual Studio Code', '1.96+'],
      ['Runtime', 'Node.js', '18.x LTS'],
      ['Database', 'MongoDB Atlas', '7.0'],
      ['Package Manager', 'npm', '9.x'],
      ['Version Control', 'Git', '2.43'],
      ['Browser Test', 'Google Chrome', '120+'],
      ['API Testing', 'Postman', '10.x'],
    ]),
    empty(),
    h2('4.2. Giao diện người dùng'),
    h3('4.2.1. Trang chủ (HomePage)'),
    p('Trang chủ hiển thị banner quảng cáo (có thể quản lý từ admin), thanh tìm kiếm nổi bật ở vị trí trung tâm cho phép người dùng nhập địa điểm, ngày nhận/trả phòng và số khách. Bên dưới là danh sách các khách sạn nổi bật (featured hotels) được hiển thị dưới dạng card với hình ảnh, tên, địa chỉ, đánh giá sao và khoảng giá. Trang cũng hiển thị các bài viết/tin tức mới nhất về du lịch.'),
    p('Giao diện sử dụng Tailwind CSS với gradient background, shadow effects và animations để tạo cảm giác hiện đại, chuyên nghiệp. Trên mobile, layout chuyển sang dạng stack (1 cột) để đảm bảo trải nghiệm tốt.'),
    h3('4.2.2. Trang danh sách khách sạn (HotelListPage)'),
    p('Trang hiển thị danh sách khách sạn với các bộ lọc phong phú: theo thành phố/địa điểm, khoảng giá (slider), đánh giá tối thiểu, tiện nghi. Hỗ trợ sắp xếp theo giá (tăng/giảm), đánh giá, mới nhất. Phân trang (pagination) để tải nhanh khi có nhiều kết quả.'),
    p('Mỗi khách sạn được hiển thị dưới dạng HotelCard component với: ảnh thumbnail, tên khách sạn, địa chỉ rút gọn, số sao đánh giá, khoảng giá/đêm, và nút "Xem chi tiết". Có chế độ xem danh sách (list view) và lưới (grid view).'),
    h3('4.2.3. Trang chi tiết khách sạn (HotelDetailPage)'),
    p('Trang chi tiết hiển thị đầy đủ thông tin khách sạn: gallery hình ảnh (image carousel), mô tả chi tiết, danh sách tiện nghi (wifi, hồ bơi, bãi đỗ xe...), thông tin liên hệ, và bản đồ vị trí. Phần quan trọng nhất là danh sách phòng trống với thông tin: tên loại phòng, giá/đêm, sức chứa, tiện nghi phòng, hình ảnh, và nút "Đặt phòng".'),
    p('Bên dưới là khu vực đánh giá (reviews) hiển thị các nhận xét từ khách hàng đã sử dụng dịch vụ, bao gồm: tên người đánh giá, avatar, số sao, nội dung nhận xét, ngày đánh giá. Người dùng đã check-out có thể viết đánh giá mới.'),
    h3('4.2.4. Trang đặt phòng (BookingPage)'),
    p('Trang đặt phòng được thiết kế theo dạng multi-step form: Bước 1 - Chọn phòng và số lượng, ngày nhận/trả; Bước 2 - Nhập thông tin khách (họ tên, email, điện thoại, ghi chú); Bước 3 - Áp dụng mã giảm giá, xem tóm tắt chi phí; Bước 4 - Chọn phương thức thanh toán.'),
    p('Hệ thống tự động tính tổng tiền dựa trên: số phòng × giá/đêm × số đêm - giảm giá (nếu có). Hiển thị rõ ràng chi tiết từng khoản để người dùng nắm rõ trước khi thanh toán.'),
    h3('4.2.5. Trang thanh toán (PaymentPage)'),
    p('Sau khi xác nhận đặt phòng, người dùng được chuyển đến trang thanh toán với hai lựa chọn: VNPay (thẻ ATM nội địa, Visa/Master/JCB, VNPay QR) hoặc MoMo (quét QR code, ví MoMo). Khi chọn, hệ thống tạo URL thanh toán và redirect người dùng đến trang gateway tương ứng.'),
    p('Sau khi hoàn tất thanh toán (hoặc hủy), gateway callback về hệ thống qua return URL. Hệ thống verify chữ ký (signature), cập nhật trạng thái thanh toán và đặt phòng, sau đó hiển thị trang xác nhận kết quả.'),
    h3('4.2.6. Trang xác nhận đặt phòng (BookingConfirmationPage)'),
    p('Hiển thị thông tin đặt phòng thành công: mã booking (để tra cứu sau này), thông tin khách sạn/phòng, ngày nhận/trả phòng, tổng tiền đã thanh toán, phương thức thanh toán, trạng thái. Có nút chuyển đến "Đặt phòng của tôi" để xem lịch sử.'),
    h3('4.2.7. Chatbot (Chatbot Component)'),
    p('Chatbot được hiển thị dưới dạng floating widget ở góc phải bên dưới màn hình. Khi click vào icon chat, popup mở ra hiển thị giao diện chat: lịch sử tin nhắn, ô nhập tin nhắn, nút gửi. Chatbot sử dụng Google Gemini API để xử lý ngôn ngữ tự nhiên, có thể trả lời các câu hỏi về: thông tin khách sạn, giá phòng, chính sách đặt/hủy phòng, gợi ý khách sạn phù hợp, hướng dẫn sử dụng website.'),
    h3('4.2.8. Các trang khác'),
    bullet('Trang đăng nhập/đăng ký: Form validation real-time, hiển thị lỗi rõ ràng, link "Quên mật khẩu".'),
    bullet('Trang profile: Cho phép cập nhật thông tin cá nhân, đổi avatar (upload lên Cloudinary), đổi mật khẩu.'),
    bullet('Trang "Đặt phòng của tôi" (MyBookingsPage): Danh sách tất cả booking với trạng thái, cho phép hủy (nếu chưa check-in).'),
    bullet('Trang bài viết (ArticlesPage): Tin tức, tips du lịch được quản trị viên đăng tải.'),
    bullet('Trang tra cứu booking (BookingLookupPage): Nhập mã booking để xem chi tiết mà không cần đăng nhập.'),
    bullet('Trang liên hệ (ContactPage): Form gửi tin nhắn đến admin.'),
    empty(),
    h2('4.3. Giao diện quản trị (Admin Panel)'),
    h3('4.3.1. Dashboard'),
    p('Trang tổng quan hiển thị các thống kê quan trọng: tổng số booking (hôm nay, tuần này, tháng này), doanh thu, số khách sạn, số người dùng, số đánh giá. Biểu đồ doanh thu theo thời gian, top khách sạn có nhiều booking nhất. Danh sách booking mới nhất cần xử lý.'),
    h3('4.3.2. Quản lý khách sạn'),
    p('CRUD đầy đủ: Danh sách khách sạn dạng bảng (tên, thành phố, số phòng, đánh giá, trạng thái). Form thêm/sửa khách sạn với: upload nhiều hình ảnh (drag & drop), rich text editor cho mô tả, checkbox tiện nghi, nhập địa chỉ. Nút xóa có xác nhận (confirm dialog).'),
    h3('4.3.3. Quản lý phòng'),
    p('Quản lý phòng theo từng khách sạn: xem danh sách phòng, thêm phòng mới, cập nhật giá/số lượng/trạng thái, upload hình ảnh phòng, xóa phòng. Filter theo khách sạn, trạng thái khả dụng.'),
    h3('4.3.4. Quản lý đặt phòng'),
    p('Danh sách tất cả booking với bộ lọc: theo trạng thái (pending, confirmed, checked_in, checked_out, cancelled), theo khách sạn, theo ngày. Admin có thể: xác nhận booking, check-in/check-out khách, hủy booking. Xem chi tiết đầy đủ thông tin booking, thông tin thanh toán.'),
    h3('4.3.5. Quản lý người dùng'),
    p('Danh sách user với thông tin: tên, email, role, ngày đăng ký, trạng thái. Admin có thể: xem chi tiết, khóa/mở khóa tài khoản, thay đổi role. Tìm kiếm user theo tên hoặc email.'),
    h3('4.3.6. Quản lý khác'),
    bullet('Quản lý đánh giá: Phê duyệt, ẩn review vi phạm, xem thống kê rating.'),
    bullet('Quản lý mã giảm giá: Tạo coupon (phần trăm hoặc số tiền cố định), đặt hạn sử dụng, giới hạn số lần dùng.'),
    bullet('Quản lý bài viết: Tạo, sửa, xóa bài viết/tin tức, upload hình ảnh cho bài viết.'),
    bullet('Quản lý banner: Cập nhật hình ảnh banner trang chủ.'),
    bullet('Tin nhắn liên hệ: Xem và phản hồi tin nhắn từ trang Contact.'),
    empty(),
    h2('4.4. Kiểm thử hệ thống'),
    h3('4.4.1. Kiểm thử chức năng (Functional Testing)'),
    makeTable(['STT', 'Chức năng', 'Mô tả kiểm thử', 'Kết quả'], [
      ['1', 'Đăng ký', 'Đăng ký với thông tin hợp lệ/không hợp lệ', 'Đạt'],
      ['2', 'Đăng nhập', 'Đăng nhập đúng/sai mật khẩu, token refresh', 'Đạt'],
      ['3', 'Tìm kiếm KS', 'Tìm theo tên, thành phố, giá, rating', 'Đạt'],
      ['4', 'Xem chi tiết', 'Hiển thị đầy đủ thông tin, hình ảnh, reviews', 'Đạt'],
      ['5', 'Đặt phòng', 'Đặt phòng thành công, kiểm tra available', 'Đạt'],
      ['6', 'Thanh toán VNPay', 'Tạo URL, redirect, callback, verify', 'Đạt'],
      ['7', 'Thanh toán MoMo', 'Tạo URL, redirect, callback, verify', 'Đạt'],
      ['8', 'Áp dụng coupon', 'Mã hợp lệ, hết hạn, đã dùng hết', 'Đạt'],
      ['9', 'Hủy booking', 'Hủy khi chưa check-in, không hủy khi đã check-in', 'Đạt'],
      ['10', 'Đánh giá', 'Viết review sau check-out, validation rating', 'Đạt'],
      ['11', 'Chatbot', 'Gửi câu hỏi, nhận phản hồi AI phù hợp', 'Đạt'],
      ['12', 'Thông báo RT', 'Nhận notification khi booking thay đổi', 'Đạt'],
      ['13', 'Upload ảnh', 'Upload avatar, ảnh KS, ảnh phòng lên Cloudinary', 'Đạt'],
      ['14', 'Quên mật khẩu', 'Gửi email reset, đặt lại mật khẩu', 'Đạt'],
      ['15', 'Tra cứu booking', 'Nhập mã booking, hiển thị chi tiết', 'Đạt'],
      ['16', 'Admin CRUD', 'Thêm/sửa/xóa khách sạn, phòng, user', 'Đạt'],
      ['17', 'Phân quyền', 'User không truy cập được admin, guest không đặt phòng', 'Đạt'],
      ['18', 'Responsive', 'Kiểm tra trên mobile, tablet, desktop', 'Đạt'],
    ]),
    p('Bảng 4.1. Kết quả kiểm thử chức năng', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    h3('4.4.2. Kiểm thử hiệu suất'),
    makeTable(['Chỉ số', 'Mục tiêu', 'Kết quả', 'Đánh giá'], [
      ['Thời gian tải trang chủ', '< 3 giây', '1.8 giây', 'Đạt'],
      ['Thời gian phản hồi API (trung bình)', '< 500ms', '120ms', 'Đạt'],
      ['Thời gian phản hồi API (P95)', '< 1000ms', '450ms', 'Đạt'],
      ['Lighthouse Performance Score', '> 80', '89', 'Đạt'],
      ['Lighthouse Accessibility', '> 80', '92', 'Đạt'],
      ['First Contentful Paint', '< 2s', '1.2s', 'Đạt'],
      ['Largest Contentful Paint', '< 3s', '2.1s', 'Đạt'],
      ['Bundle size (gzipped)', '< 500KB', '380KB', 'Đạt'],
    ]),
    p('Bảng 4.2. Kết quả kiểm thử hiệu suất', { align: AlignmentType.CENTER, italic: true, noIndent: true }),
    empty(),
    h3('4.4.3. Kiểm thử bảo mật'),
    p('Hệ thống đã được kiểm tra và đảm bảo các yêu cầu bảo mật cơ bản:'),
    bullet('Mật khẩu được hash bằng bcrypt với salt rounds = 10, không lưu plaintext.'),
    bullet('JWT access token có thời hạn ngắn (1 ngày), refresh token được lưu trong httpOnly cookie.'),
    bullet('Rate limiting trên các endpoint nhạy cảm (login, register, forgot-password).'),
    bullet('Input validation và sanitization trên tất cả API endpoints (express-validator).'),
    bullet('CORS configuration chỉ cho phép origin từ frontend.'),
    bullet('File upload validation: kiểm tra mime type, giới hạn kích thước (5MB).'),
    bullet('SQL Injection: Không áp dụng (NoSQL), nhưng có sanitize input chống NoSQL injection.'),
    bullet('XSS: React tự động escape output, Tailwind CSS không sử dụng dangerouslySetInnerHTML.'),
  ]
};

// ======================== CHAPTER 5 ========================
const chapter5 = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('CHƯƠNG 5', 28, true),
    center('KẾT LUẬN VÀ HƯỚNG PHÁT TRIỂN', 28, true), empty(),
    h2('5.1. Kết luận'),
    p('Sau quá trình nghiên cứu, phân tích, thiết kế và xây dựng, tiểu luận đã hoàn thành được các mục tiêu đề ra ban đầu. Cụ thể, hệ thống website đặt phòng khách sạn trực tuyến đã được phát triển thành công với các kết quả đạt được như sau:'),
    bullet('Xây dựng thành công website đặt phòng khách sạn trực tuyến full-stack sử dụng MERN Stack, hoạt động ổn định và hiệu quả.'),
    bullet('Giao diện người dùng hiện đại, trực quan, tương thích đa thiết bị (responsive), mang lại trải nghiệm tốt cho người dùng.'),
    bullet('Tích hợp thành công hai cổng thanh toán phổ biến tại Việt Nam (VNPay và MoMo), đáp ứng nhu cầu thanh toán đa dạng.'),
    bullet('Chatbot AI sử dụng Google Gemini hoạt động tốt, có khả năng tư vấn và hỗ trợ khách hàng 24/7.'),
    bullet('Hệ thống thông báo real-time với Socket.IO giúp admin và user nắm bắt kịp thời các thay đổi.'),
    bullet('Trang quản trị đầy đủ chức năng, giúp quản lý hiệu quả toàn bộ hệ thống.'),
    bullet('Bảo mật tốt với JWT authentication, rate limiting, input validation.'),
    bullet('Kiểm thử đạt yêu cầu về chức năng và hiệu suất.'),
    p('Về mặt học thuật, đề tài đã giúp em nắm vững kiến thức về:'),
    bullet('Kiến trúc ứng dụng web full-stack hiện đại.'),
    bullet('Thiết kế RESTful API và cơ sở dữ liệu NoSQL.'),
    bullet('Quản lý state trong ứng dụng React lớn với Redux Toolkit.'),
    bullet('Tích hợp dịch vụ bên thứ ba (payment gateway, AI, cloud storage).'),
    bullet('Real-time communication với WebSocket/Socket.IO.'),
    bullet('Quy trình phát triển phần mềm: phân tích, thiết kế, code, test, deploy.'),
    empty(),
    h2('5.2. Hạn chế'),
    p('Mặc dù đã cố gắng hoàn thiện, hệ thống vẫn còn một số hạn chế cần khắc phục:'),
    bullet('Chưa triển khai trên môi trường production (cloud hosting), mới chạy ở môi trường development.'),
    bullet('Thanh toán chạy ở chế độ sandbox/test, chưa kết nối tài khoản merchant thật.'),
    bullet('Chưa hỗ trợ đa ngôn ngữ (i18n), hiện tại chỉ có tiếng Việt.'),
    bullet('Chưa tích hợp bản đồ (Google Maps) để hiển thị vị trí khách sạn.'),
    bullet('Chưa có tính năng so sánh khách sạn/phòng.'),
    bullet('Chatbot chưa có memory dài hạn, mỗi phiên chat là độc lập.'),
    bullet('Chưa có unit test và integration test tự động (chỉ test thủ công).'),
    bullet('SEO chưa được tối ưu hoàn toàn (SPA limitation).'),
    empty(),
    h2('5.3. Hướng phát triển'),
    p('Dựa trên các hạn chế đã nêu và xu hướng phát triển công nghệ, em đề xuất các hướng phát triển trong tương lai:'),
    bullet('Triển khai production: Deploy backend lên AWS/Google Cloud, frontend lên Vercel/Netlify, database MongoDB Atlas.'),
    bullet('Tích hợp bản đồ: Sử dụng Google Maps API hoặc Mapbox để hiển thị vị trí khách sạn, tìm kiếm theo khu vực.'),
    bullet('Đa ngôn ngữ: Tích hợp i18next để hỗ trợ tiếng Việt và tiếng Anh.'),
    bullet('Progressive Web App (PWA): Chuyển đổi sang PWA để hỗ trợ offline, push notification, install-able.'),
    bullet('AI nâng cao: Mở rộng chatbot với recommendation system, gợi ý khách sạn dựa trên lịch sử đặt phòng.'),
    bullet('Mobile App: Phát triển ứng dụng mobile bằng React Native, tái sử dụng logic từ web app.'),
    bullet('Server-Side Rendering: Chuyển sang Next.js để cải thiện SEO và First Load Performance.'),
    bullet('Automated Testing: Viết unit test (Jest), integration test (Supertest), E2E test (Cypress/Playwright).'),
    bullet('CI/CD Pipeline: Thiết lập GitHub Actions cho automated testing và deployment.'),
    bullet('Microservices: Tách thành các service nhỏ (auth service, booking service, payment service) khi scale lên.'),
  ]
};

// ======================== REFERENCES ========================
const references = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('TÀI LIỆU THAM KHẢO', 28, true), empty(),
    p('Tiếng Việt:', { bold: true, noIndent: true }),
    p('[1] Nguyễn Văn Vỵ (2020), Phân tích và thiết kế hệ thống thông tin, NXB Đại học Quốc gia Hà Nội.', { noIndent: true }),
    p('[2] Trần Đình Quế (2019), Nhập môn Công nghệ phần mềm, NXB Giáo dục Việt Nam.', { noIndent: true }),
    p('[3] Phạm Hữu Khang (2021), Lập trình Web với JavaScript, NXB Thống kê.', { noIndent: true }),
    empty(),
    p('Tiếng Anh:', { bold: true, noIndent: true }),
    p('[4] Subramanian, V. (2019), Pro MERN Stack: Full Stack Web App Development with Mongo, Express, React, and Node, 2nd Edition, Apress.', { noIndent: true }),
    p('[5] Mardan, A. (2018), Full Stack JavaScript: Learn Backbone.js, Node.js, and MongoDB, 2nd Edition, Apress.', { noIndent: true }),
    p('[6] Flanagan, D. (2020), JavaScript: The Definitive Guide, 7th Edition, O\'Reilly Media.', { noIndent: true }),
    p('[7] Brown, E. (2019), Web Development with Node and Express, 2nd Edition, O\'Reilly Media.', { noIndent: true }),
    p('[8] Banks, A. & Porcello, E. (2020), Learning React: Modern Patterns for Developing React Apps, 2nd Edition, O\'Reilly Media.', { noIndent: true }),
    p('[9] Bradshaw, S. et al. (2019), MongoDB: The Definitive Guide, 3rd Edition, O\'Reilly Media.', { noIndent: true }),
    p('[10] Casciaro, M. & Mammino, L. (2020), Node.js Design Patterns, 3rd Edition, Packt Publishing.', { noIndent: true }),
    empty(),
    p('Tài liệu trực tuyến:', { bold: true, noIndent: true }),
    p('[11] React Official Documentation, https://react.dev/', { noIndent: true }),
    p('[12] MongoDB Documentation, https://docs.mongodb.com/', { noIndent: true }),
    p('[13] Express.js Guide, https://expressjs.com/en/guide/', { noIndent: true }),
    p('[14] Node.js Documentation, https://nodejs.org/docs/', { noIndent: true }),
    p('[15] Redux Toolkit Documentation, https://redux-toolkit.js.org/', { noIndent: true }),
    p('[16] Socket.IO Documentation, https://socket.io/docs/', { noIndent: true }),
    p('[17] Tailwind CSS Documentation, https://tailwindcss.com/docs', { noIndent: true }),
    p('[18] VNPay Developer Documentation, https://sandbox.vnpayment.vn/apis/', { noIndent: true }),
    p('[19] MoMo Developer Documentation, https://developers.momo.vn/', { noIndent: true }),
    p('[20] Google Gemini API Documentation, https://ai.google.dev/docs', { noIndent: true }),
    p('[21] Cloudinary Documentation, https://cloudinary.com/documentation', { noIndent: true }),
    p('[22] Vite Documentation, https://vitejs.dev/guide/', { noIndent: true }),
    p('[23] JSON Web Token (RFC 7519), https://tools.ietf.org/html/rfc7519', { noIndent: true }),
  ]
};

// ======================== APPENDIX ========================
const appendix = {
  properties: { page: { margin: margins } },
  children: [
    pageBreak(),
    center('PHỤ LỤC', 28, true), empty(),
    h2('Phụ lục A: Hướng dẫn cài đặt và chạy hệ thống'),
    empty(),
    h3('A.1. Yêu cầu hệ thống'),
    bullet('Node.js >= 18.x (LTS)'),
    bullet('npm >= 9.x'),
    bullet('MongoDB (local hoặc MongoDB Atlas)'),
    bullet('Git'),
    empty(),
    h3('A.2. Cài đặt Backend (Server)'),
    p('Bước 1: Di chuyển vào thư mục server', { noIndent: true }),
    p('$ cd hotel/server', { noIndent: true, italic: true }),
    p('Bước 2: Cài đặt dependencies', { noIndent: true }),
    p('$ npm install', { noIndent: true, italic: true }),
    p('Bước 3: Tạo file .env với các biến môi trường (xem Phụ lục B)', { noIndent: true }),
    p('Bước 4: Khởi động server', { noIndent: true }),
    p('$ npm run dev', { noIndent: true, italic: true }),
    p('Server sẽ chạy tại http://localhost:5000', { noIndent: true }),
    empty(),
    h3('A.3. Cài đặt Frontend (Client)'),
    p('Bước 1: Di chuyển vào thư mục client', { noIndent: true }),
    p('$ cd hotel/client', { noIndent: true, italic: true }),
    p('Bước 2: Cài đặt dependencies', { noIndent: true }),
    p('$ npm install', { noIndent: true, italic: true }),
    p('Bước 3: Khởi động development server', { noIndent: true }),
    p('$ npm run dev', { noIndent: true, italic: true }),
    p('Frontend sẽ chạy tại http://localhost:5173', { noIndent: true }),
    empty(),
    h2('Phụ lục B: Cấu hình biến môi trường (.env)'),
    empty(),
    p('File .env cho Backend Server:', { bold: true, noIndent: true }),
    p('PORT=5000', { noIndent: true, italic: true }),
    p('MONGODB_URI=mongodb+srv://<user>:<pass>@cluster.mongodb.net/hotel_booking', { noIndent: true, italic: true }),
    p('JWT_ACCESS_SECRET=your_access_secret_key', { noIndent: true, italic: true }),
    p('JWT_REFRESH_SECRET=your_refresh_secret_key', { noIndent: true, italic: true }),
    p('JWT_ACCESS_EXPIRES=1d', { noIndent: true, italic: true }),
    p('JWT_REFRESH_EXPIRES=7d', { noIndent: true, italic: true }),
    p('CLOUDINARY_CLOUD_NAME=your_cloud_name', { noIndent: true, italic: true }),
    p('CLOUDINARY_API_KEY=your_api_key', { noIndent: true, italic: true }),
    p('CLOUDINARY_API_SECRET=your_api_secret', { noIndent: true, italic: true }),
    p('VNPAY_TMN_CODE=your_vnpay_tmn_code', { noIndent: true, italic: true }),
    p('VNPAY_HASH_SECRET=your_vnpay_hash_secret', { noIndent: true, italic: true }),
    p('VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html', { noIndent: true, italic: true }),
    p('VNPAY_RETURN_URL=http://localhost:5173/vnpay-return', { noIndent: true, italic: true }),
    p('MOMO_PARTNER_CODE=your_momo_partner_code', { noIndent: true, italic: true }),
    p('MOMO_ACCESS_KEY=your_momo_access_key', { noIndent: true, italic: true }),
    p('MOMO_SECRET_KEY=your_momo_secret_key', { noIndent: true, italic: true }),
    p('MOMO_ENDPOINT=https://test-payment.momo.vn/v2/gateway/api/create', { noIndent: true, italic: true }),
    p('GEMINI_API_KEY=your_gemini_api_key', { noIndent: true, italic: true }),
    p('CLIENT_URL=http://localhost:5173', { noIndent: true, italic: true }),
    p('EMAIL_USER=your_email@gmail.com', { noIndent: true, italic: true }),
    p('EMAIL_PASS=your_app_password', { noIndent: true, italic: true }),
    empty(),
    h2('Phụ lục C: Hướng dẫn sử dụng hệ thống'),
    empty(),
    h3('C.1. Đối với khách hàng'),
    p('1. Truy cập website tại địa chỉ http://localhost:5173', { noIndent: true }),
    p('2. Đăng ký tài khoản hoặc đăng nhập nếu đã có tài khoản.', { noIndent: true }),
    p('3. Sử dụng thanh tìm kiếm để tìm khách sạn theo địa điểm, ngày, số khách.', { noIndent: true }),
    p('4. Click vào khách sạn để xem chi tiết thông tin và danh sách phòng.', { noIndent: true }),
    p('5. Chọn phòng muốn đặt, nhập thông tin khách và tiến hành thanh toán.', { noIndent: true }),
    p('6. Sau khi thanh toán thành công, nhận mã booking để tra cứu.', { noIndent: true }),
    p('7. Có thể sử dụng chatbot (icon chat góc phải dưới) để được tư vấn.', { noIndent: true }),
    empty(),
    h3('C.2. Đối với quản trị viên'),
    p('1. Đăng nhập với tài khoản admin.', { noIndent: true }),
    p('2. Truy cập trang admin tại /admin/dashboard.', { noIndent: true }),
    p('3. Quản lý khách sạn: Thêm mới, cập nhật thông tin, upload hình ảnh.', { noIndent: true }),
    p('4. Quản lý phòng: Thêm phòng cho từng khách sạn, đặt giá, số lượng.', { noIndent: true }),
    p('5. Quản lý đặt phòng: Xác nhận booking, check-in/check-out khách.', { noIndent: true }),
    p('6. Quản lý mã giảm giá: Tạo coupon cho chiến dịch marketing.', { noIndent: true }),
    p('7. Quản lý nội dung: Đăng bài viết, cập nhật banner.', { noIndent: true }),
    p('8. Xem thống kê doanh thu và hoạt động hệ thống.', { noIndent: true }),
  ]
};

// ======================== BUILD DOCUMENT ========================
const doc = new Document({
  styles: { default: { document: { run: { font: FONT, size: SZ }, paragraph: { spacing: { line: 288 } } } } },
  sections: [coverPage, acknowledgments, commitment, abstractPage, tocPage, chapter1, chapter2, chapter3, chapter4, chapter5, references, appendix],
});

const buffer = await Packer.toBuffer(doc);
fs.writeFileSync('d:\\DATN2026\\BaoCao_TieuLuan_DatPhongKhachSan.docx', buffer);
console.log(`Done! File size: ${(buffer.length / 1024).toFixed(1)} KB`);
